version: '3.8'

services:
  go:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./db/.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server/src
        target: /go/src

  db:
    container_name: database
    build:
      context: ./db
      dockerfile: Dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./db/.env
    volumes:
      - type: volume
        source: oruka_db
        target: /var/lib/mysql
      - type: bind
        source: ./db/init
        target: /docker-entrypoint-initdb.d

volumes:
  oruka_db:
    name: oruka_db
