// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"oruka/ent/predicate"
	"oruka/ent/timerecord"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TimeRecordDelete is the builder for deleting a TimeRecord entity.
type TimeRecordDelete struct {
	config
	hooks    []Hook
	mutation *TimeRecordMutation
}

// Where appends a list predicates to the TimeRecordDelete builder.
func (trd *TimeRecordDelete) Where(ps ...predicate.TimeRecord) *TimeRecordDelete {
	trd.mutation.Where(ps...)
	return trd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (trd *TimeRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, TimeRecordMutation](ctx, trd.sqlExec, trd.mutation, trd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (trd *TimeRecordDelete) ExecX(ctx context.Context) int {
	n, err := trd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (trd *TimeRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(timerecord.Table, sqlgraph.NewFieldSpec(timerecord.FieldID, field.TypeInt))
	if ps := trd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, trd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	trd.mutation.done = true
	return affected, err
}

// TimeRecordDeleteOne is the builder for deleting a single TimeRecord entity.
type TimeRecordDeleteOne struct {
	trd *TimeRecordDelete
}

// Where appends a list predicates to the TimeRecordDelete builder.
func (trdo *TimeRecordDeleteOne) Where(ps ...predicate.TimeRecord) *TimeRecordDeleteOne {
	trdo.trd.mutation.Where(ps...)
	return trdo
}

// Exec executes the deletion query.
func (trdo *TimeRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := trdo.trd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{timerecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (trdo *TimeRecordDeleteOne) ExecX(ctx context.Context) {
	if err := trdo.Exec(ctx); err != nil {
		panic(err)
	}
}
