// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"oruka/ent/timerecord"
	"oruka/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TimeRecordCreate is the builder for creating a TimeRecord entity.
type TimeRecordCreate struct {
	config
	mutation *TimeRecordMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (trc *TimeRecordCreate) SetCreatedAt(t time.Time) *TimeRecordCreate {
	trc.mutation.SetCreatedAt(t)
	return trc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (trc *TimeRecordCreate) SetNillableCreatedAt(t *time.Time) *TimeRecordCreate {
	if t != nil {
		trc.SetCreatedAt(*t)
	}
	return trc
}

// SetUpdatedAt sets the "updated_at" field.
func (trc *TimeRecordCreate) SetUpdatedAt(t time.Time) *TimeRecordCreate {
	trc.mutation.SetUpdatedAt(t)
	return trc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (trc *TimeRecordCreate) SetNillableUpdatedAt(t *time.Time) *TimeRecordCreate {
	if t != nil {
		trc.SetUpdatedAt(*t)
	}
	return trc
}

// SetTimeKeeperID sets the "timeKeeper" edge to the User entity by ID.
func (trc *TimeRecordCreate) SetTimeKeeperID(id int) *TimeRecordCreate {
	trc.mutation.SetTimeKeeperID(id)
	return trc
}

// SetNillableTimeKeeperID sets the "timeKeeper" edge to the User entity by ID if the given value is not nil.
func (trc *TimeRecordCreate) SetNillableTimeKeeperID(id *int) *TimeRecordCreate {
	if id != nil {
		trc = trc.SetTimeKeeperID(*id)
	}
	return trc
}

// SetTimeKeeper sets the "timeKeeper" edge to the User entity.
func (trc *TimeRecordCreate) SetTimeKeeper(u *User) *TimeRecordCreate {
	return trc.SetTimeKeeperID(u.ID)
}

// Mutation returns the TimeRecordMutation object of the builder.
func (trc *TimeRecordCreate) Mutation() *TimeRecordMutation {
	return trc.mutation
}

// Save creates the TimeRecord in the database.
func (trc *TimeRecordCreate) Save(ctx context.Context) (*TimeRecord, error) {
	trc.defaults()
	return withHooks[*TimeRecord, TimeRecordMutation](ctx, trc.sqlSave, trc.mutation, trc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (trc *TimeRecordCreate) SaveX(ctx context.Context) *TimeRecord {
	v, err := trc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (trc *TimeRecordCreate) Exec(ctx context.Context) error {
	_, err := trc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (trc *TimeRecordCreate) ExecX(ctx context.Context) {
	if err := trc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (trc *TimeRecordCreate) defaults() {
	if _, ok := trc.mutation.CreatedAt(); !ok {
		v := timerecord.DefaultCreatedAt()
		trc.mutation.SetCreatedAt(v)
	}
	if _, ok := trc.mutation.UpdatedAt(); !ok {
		v := timerecord.DefaultUpdatedAt()
		trc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (trc *TimeRecordCreate) check() error {
	if _, ok := trc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TimeRecord.created_at"`)}
	}
	if _, ok := trc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TimeRecord.updated_at"`)}
	}
	return nil
}

func (trc *TimeRecordCreate) sqlSave(ctx context.Context) (*TimeRecord, error) {
	if err := trc.check(); err != nil {
		return nil, err
	}
	_node, _spec := trc.createSpec()
	if err := sqlgraph.CreateNode(ctx, trc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	trc.mutation.id = &_node.ID
	trc.mutation.done = true
	return _node, nil
}

func (trc *TimeRecordCreate) createSpec() (*TimeRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &TimeRecord{config: trc.config}
		_spec = sqlgraph.NewCreateSpec(timerecord.Table, sqlgraph.NewFieldSpec(timerecord.FieldID, field.TypeInt))
	)
	if value, ok := trc.mutation.CreatedAt(); ok {
		_spec.SetField(timerecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := trc.mutation.UpdatedAt(); ok {
		_spec.SetField(timerecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := trc.mutation.TimeKeeperIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timerecord.TimeKeeperTable,
			Columns: []string{timerecord.TimeKeeperColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_time_records = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TimeRecordCreateBulk is the builder for creating many TimeRecord entities in bulk.
type TimeRecordCreateBulk struct {
	config
	builders []*TimeRecordCreate
}

// Save creates the TimeRecord entities in the database.
func (trcb *TimeRecordCreateBulk) Save(ctx context.Context) ([]*TimeRecord, error) {
	specs := make([]*sqlgraph.CreateSpec, len(trcb.builders))
	nodes := make([]*TimeRecord, len(trcb.builders))
	mutators := make([]Mutator, len(trcb.builders))
	for i := range trcb.builders {
		func(i int, root context.Context) {
			builder := trcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TimeRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, trcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, trcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, trcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (trcb *TimeRecordCreateBulk) SaveX(ctx context.Context) []*TimeRecord {
	v, err := trcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (trcb *TimeRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := trcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (trcb *TimeRecordCreateBulk) ExecX(ctx context.Context) {
	if err := trcb.Exec(ctx); err != nil {
		panic(err)
	}
}
