// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TimeRecord is the predicate function for timerecord builders.
type TimeRecord func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
